name: Generate README Stats

on:
  schedule:
    - cron: '0 */12 * * *' # Updates your stats automatically every 12 hours
  workflow_dispatch: # Allows you to run it manually

permissions:
  contents: write # Gives permission to write files

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Generate Stats Images
        uses: ryo-ma/github-profile-trophy@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          username: vikasjadhav-dev
          output_path: trophy.svg

      - name: Commit & Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update profile stats"
          file_pattern: 'trophy.svg'
