name: Generate README Stats

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch: # Allows you to run it manually

permissions:
  contents: write # 👈 Added: Gives the Action permission to save the image to your repository

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Generate Stats Images
        uses: ryo-ma/github-profile-trophy@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          username: vikasjadhav-dev
          output_path: trophy.svg # 👈 Added: Tells the script what name to give the file

      - name: Commit & Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update profile stats" || exit 0
          git push
